apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wikijs-keyvault
  namespace: wikijs

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"

    clientID: "7152460b-ae70-4dd7-9d83-de3d87257697"

    keyvaultName: "wikijsprodaib1kv"

    tenantId: "6a0c8737-9bb9-4711-ac43-a25c5f8c001b"

    objects: |
      array:
        - |
          objectName: wikijs-db-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: wikijs-db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: wikijs-db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: wikijs-db-name
          objectType: secret
          objectVersion: ""
